### ISSUE TITLE
syscall error check is wrong

### ISSUE THREAD

**Issue by pcordes** [JL2210/minilibc#1]
After `int 0x80` / `syscall`, any EAX/RAX value above (unsigned) -4096ULL is an error.  Your current code [`cmp $-0x0fff, %rax` / `je`](https://github.com/JL2210/minilibc/blob/8365e9a2f03ef376f9937070b8ba2cf4eb99b6ae/arch/x86_64/src/stdlib/syscall.s#L13) only checks for the lowest such value, `-4095`, which is currently unused as a Linux error code.

The correct way to check is this (or the same but with EAX in 32-bit mode):

```
cmp  $-4096, %rax       # unsigned 2^32 - 4096, aka signed -4096
ja    error
```

That's what glibc does: https://stackoverflow.com/questions/18996410/linux-kernel-system-call-returns-1-instead-of-1-256/18998521#18998521, and is guaranteed to work for *all* system calls, present and future.

Also don't forget a TODO: errno in there.

For code-size, you might consider `or $-1, %rax` in the error path.  1st of all it's rarely executed, and there's normally a serializing instruction in the system-call return path so the "false" dependency on the old value of RAX is not important.

**Comment by JL2210** [comment]
Thanks! I'll fix this.

**Comment by JL2210** [comment]
So is this right?
```
        pop %ebp
        or $-1, %eax
        ret
```
64-bit:
```
        syscall
        or $-1, %rax
        ret
```
